from typing import List, Dict

FEATURE_ORDER: List[str] = [
    "lex_avg_word_len",
    "lex_ttr_lemma",
    "lex_share_stop",
    "lex_share_num_symbol",
    "lex_share_oov",
    "lex_share_awl",
    "lex_avg_syll_per_word",
    "syn_avg_sentence_length",
    "syn_avg_clause_per_sentence",
    "syn_share_complex_sentences",
    "syn_share_passive_sentences",
    "syn_avg_dependency_depth",
    "syn_share_sub_conjs",
    "syn_avg_coord_per_sentence",
    "morph_share_nouns",
    "morph_share_verbs",
    "morph_share_adj",
    "morph_share_adv",
    "morph_share_pronouns",
    "morph_share_propn",
    "morph_share_aux",
    "morph_share_modals",
    "morph_tense_past_share",
    "morph_tense_present_share",
    "morph_share_perfect",
    "morph_share_progressive",
    "morph_share_perfect_progressive",
    "morph_share_future",
    "morph_content_function_ratio",
    "morph_avg_morphemes_per_word",
    "sem_mean_zipf",
    "sem_share_rare_zipf_lt_4",
    "sem_share_very_rare_zipf_lt_3",
    "sem_avg_polysemy",
    "sem_avg_hypernym_depth",
    "sem_avg_sent_sim",
    "sem_min_sent_sim",
    "sem_std_sent_sim",
    "sem_word_vector_dispersion",
    "read_flesch",
    "read_fkgl",
    "read_fog",
    "read_smog",
    "read_dale_chall"
]

ID2LEVEL: Dict[int, str] = {
    1: "A1",
    2: "A2",
    3: "B1",
    4: "B2",
    5: "C1",
    6: "C2",
}

LEVEL2ID: Dict[str, int] = {v: k for k, v in ID2LEVEL.items()}